# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpu_limit_capper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63pu_limit_capper.proto\"B\n\x12\x43ore_Number_Inputs\x12\x13\n\x0b\x64omain_name\x18\x01 \x01(\t\x12\x17\n\x0fnumber_of_cores\x18\x02 \x01(\x05\"B\n\x11\x43ore_Usage_Inputs\x12\x13\n\x0b\x64omain_name\x18\x01 \x01(\t\x12\x18\n\x10\x63ore_usage_limit\x18\x02 \x01(\x05\"\x1d\n\x0b\x43ore_Output\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x82\x01\n\x0e\x43puLimitCapper\x12\x38\n\x11limit_core_number\x12\x13.Core_Number_Inputs\x1a\x0c.Core_Output\"\x00\x12\x36\n\x10limit_core_usage\x12\x12.Core_Usage_Inputs\x1a\x0c.Core_Output\"\x00\x62\x06proto3')



_CORE_NUMBER_INPUTS = DESCRIPTOR.message_types_by_name['Core_Number_Inputs']
_CORE_USAGE_INPUTS = DESCRIPTOR.message_types_by_name['Core_Usage_Inputs']
_CORE_OUTPUT = DESCRIPTOR.message_types_by_name['Core_Output']
Core_Number_Inputs = _reflection.GeneratedProtocolMessageType('Core_Number_Inputs', (_message.Message,), {
  'DESCRIPTOR' : _CORE_NUMBER_INPUTS,
  '__module__' : 'cpu_limit_capper_pb2'
  # @@protoc_insertion_point(class_scope:Core_Number_Inputs)
  })
_sym_db.RegisterMessage(Core_Number_Inputs)

Core_Usage_Inputs = _reflection.GeneratedProtocolMessageType('Core_Usage_Inputs', (_message.Message,), {
  'DESCRIPTOR' : _CORE_USAGE_INPUTS,
  '__module__' : 'cpu_limit_capper_pb2'
  # @@protoc_insertion_point(class_scope:Core_Usage_Inputs)
  })
_sym_db.RegisterMessage(Core_Usage_Inputs)

Core_Output = _reflection.GeneratedProtocolMessageType('Core_Output', (_message.Message,), {
  'DESCRIPTOR' : _CORE_OUTPUT,
  '__module__' : 'cpu_limit_capper_pb2'
  # @@protoc_insertion_point(class_scope:Core_Output)
  })
_sym_db.RegisterMessage(Core_Output)

_CPULIMITCAPPER = DESCRIPTOR.services_by_name['CpuLimitCapper']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CORE_NUMBER_INPUTS._serialized_start=26
  _CORE_NUMBER_INPUTS._serialized_end=92
  _CORE_USAGE_INPUTS._serialized_start=94
  _CORE_USAGE_INPUTS._serialized_end=160
  _CORE_OUTPUT._serialized_start=162
  _CORE_OUTPUT._serialized_end=191
  _CPULIMITCAPPER._serialized_start=194
  _CPULIMITCAPPER._serialized_end=324
# @@protoc_insertion_point(module_scope)
